import { nanoid } from "nanoid";

export const KEYS_STORE = [
  [
    { id: nanoid(), label: "Esc", type: "simple-key", active: false },
    { id: nanoid(), label: "F1", type: "simple-key", active: false },
    { id: nanoid(), label: "F2", type: "simple-key", active: false },
    { id: nanoid(), label: "F3", type: "simple-key", active: false },
    { id: nanoid(), label: "F4", type: "simple-key", active: false },
    { id: nanoid(), label: "F5", type: "simple-key", active: false },
    { id: nanoid(), label: "F6", type: "simple-key", active: false },
    { id: nanoid(), label: "F7", type: "simple-key", active: false },
    { id: nanoid(), label: "F8", type: "simple-key", active: false },
    { id: nanoid(), label: "F9", type: "simple-key", active: false },
    { id: nanoid(), label: "F10", type: "simple-key", active: false },
    { id: nanoid(), label: "F11", type: "simple-key", active: false },
    { id: nanoid(), label: "F12", type: "simple-key", active: false },
  ],
  [
    { id: nanoid(), label: "` ~", type: "simple-key", active: false },
    { id: nanoid(), label: "1", type: "simple-key", active: false },
    { id: nanoid(), label: "2", type: "simple-key", active: false },
    { id: nanoid(), label: "3", type: "simple-key", active: false },
    { id: nanoid(), label: "4", type: "simple-key", active: false },
    { id: nanoid(), label: "5", type: "simple-key", active: false },
    { id: nanoid(), label: "6", type: "simple-key", active: false },
    { id: nanoid(), label: "7", type: "simple-key", active: false },
    { id: nanoid(), label: "8", type: "simple-key", active: false },
    { id: nanoid(), label: "9", type: "simple-key", active: false },
    { id: nanoid(), label: "0", type: "simple-key", active: false },
    { id: nanoid(), label: "-", type: "simple-key", active: false },
    { id: nanoid(), label: "+", type: "simple-key", active: false },
    { id: nanoid(), label: "Backspace", type: "backspace-key", active: false },
  ],
  [
    { id: nanoid(), label: "Tab", type: "tab-key", active: false },
    { id: nanoid(), label: "Q", type: "simple-key", active: false },
    { id: nanoid(), label: "W", type: "simple-key", active: false },
    { id: nanoid(), label: "E", type: "simple-key", active: false },
    { id: nanoid(), label: "R", type: "simple-key", active: false },
    { id: nanoid(), label: "T", type: "simple-key", active: false },
    { id: nanoid(), label: "Y", type: "simple-key", active: false },
    { id: nanoid(), label: "U", type: "simple-key", active: false },
    { id: nanoid(), label: "I", type: "simple-key", active: false },
    { id: nanoid(), label: "O", type: "simple-key", active: false },
    { id: nanoid(), label: "P", type: "simple-key", active: false },
    { id: nanoid(), label: "[", type: "simple-key", active: false },
    { id: nanoid(), label: "]", type: "simple-key", active: false },
    { id: nanoid(), label: `| /`, type: "slash-key", active: false },
  ],
  [
    { id: nanoid(), label: "CapsLock", type: "capslock-key", active: false },
    { id: nanoid(), label: "A", type: "simple-key", active: false },
    { id: nanoid(), label: "S", type: "simple-key", active: false },
    { id: nanoid(), label: "D", type: "simple-key", active: false },
    { id: nanoid(), label: "F", type: "simple-key", active: false },
    { id: nanoid(), label: "G", type: "simple-key", active: false },
    { id: nanoid(), label: "H", type: "simple-key", active: false },
    { id: nanoid(), label: "J", type: "simple-key", active: false },
    { id: nanoid(), label: "K", type: "simple-key", active: false },
    { id: nanoid(), label: "L", type: "simple-key", active: false },
    { id: nanoid(), label: ": ;", type: "simple-key", active: false },
    { id: nanoid(), label: `' "`, type: "simple-key", active: false },
    { id: nanoid(), label: "Enter", type: "enter-key", active: false },
  ],
  [
    { id: nanoid(), label: "Shift", type: "shift-key", active: false },
    { id: nanoid(), label: "Z", type: "simple-key", active: false },
    { id: nanoid(), label: "X", type: "simple-key", active: false },
    { id: nanoid(), label: "C", type: "simple-key", active: false },
    { id: nanoid(), label: "V", type: "simple-key", active: false },
    { id: nanoid(), label: "B", type: "simple-key", active: false },
    { id: nanoid(), label: "N", type: "simple-key", active: false },
    { id: nanoid(), label: "M", type: "simple-key", active: false },
    { id: nanoid(), label: "< ,", type: "simple-key", active: false },
    { id: nanoid(), label: "> .", type: "simple-key", active: false },
    { id: nanoid(), label: "? /", type: "simple-key", active: false },
    { id: nanoid(), label: "Shift", type: "shift-key", active: false },
  ],
  [
    { id: nanoid(), label: "Ctrl", type: "lower-level-key", active: false },
    { id: nanoid(), label: "Win", type: "lower-level-key", active: false },
    { id: nanoid(), label: "Alt", type: "lower-level-key", active: false },
    { id: nanoid(), label: "Space", type: "space-key", active: false },
    { id: nanoid(), label: "Alt", type: "lower-level-key", active: false },
    { id: nanoid(), label: "Fn", type: "lower-level-key", active: false },
    { id: nanoid(), label: "Select", type: "lower-level-key", active: false },
    { id: nanoid(), label: "Ctrl", type: "lower-level-key", active: false },
  ],
  [
    { id: nanoid(), label: "Prt Sc", type: "simple-key", active: false },
    { id: nanoid(), label: "Scroll Lock", type: "simple-key", active: false },
    { id: nanoid(), label: "Pause Break", type: "simple-key", active: false },
  ],
  [
    { id: nanoid(), label: "Insert", type: "simple-key", active: false },
    { id: nanoid(), label: "Home", type: "simple-key", active: false },
    { id: nanoid(), label: "Page Up", type: "simple-key", active: false },
    { id: nanoid(), label: "Delete", type: "simple-key", active: false },
    { id: nanoid(), label: "End", type: "simple-key", active: false },
    { id: nanoid(), label: "Page Down", type: "simple-key", active: false },
  ],
  [
    { id: nanoid(), label: "Up", type: "simple-key", active: false },
    { id: nanoid(), label: "Left", type: "simple-key", active: false },
    { id: nanoid(), label: "Down", type: "simple-key", active: false },
    { id: nanoid(), label: "Right", type: "simple-key", active: false },
  ],
];
